spring.application.name=project-collaboration-api

# Default to local
spring.profiles.active=local

# Global Mail (Mailtrap)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a03f1462875a37
spring.mail.password=9f017ad119f805
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Standardize this name for all files
project.app.jwtExpirationMs=10368000000