spring.application.name=project-collaboration-api

# 1. Database Connection Settings
# Added hibernate.dialect to stop the "Unable to determine Dialect" crash
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Force the Dialect (This fixes your current log error)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Railway Port
server.port=${PORT:8080}

# 4. JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 5. Security / JWT Settings
project.app.jwtSecret=mySecretKeyForProjectCollaborationAPI2026
project.app.jwtExpirationMs=10368000000

# 6. Mail Settings
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a03f1462875a37
spring.mail.password=9f017ad119f805
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true