spring.application.name=project-collaboration-api
# Default to local development
spring.profiles.active=local

# --- Global Settings ---
project.app.jwtSecret=mySecretKeyForProjectCollaborationAPI2026
project.app.jwtExpirationMs=10368000000

# Server Port (Dynamic for Railway, 8080 for local)
server.port=${PORT:8080}

# Mail Settings (Common for both environments)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a03f1462875a37
spring.mail.password=9f017ad119f805
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true